[SERVICE]
  log_level    info
  flush        1
  HTTP_Server  On
  HTTP_Listen  0.0.0.0
  HTTP_PORT    2020
  Health_Check On
  Parsers_File parsers.conf

# Application Logs
[INPUT]
  Name          forward
  Tag           ingredient-scan.logs
  Listen        0.0.0.0
  Port          24224

[FILTER]
  Name          parser
  Match         ingredient-scan.*
  Key_Name      message
  Parser        json
  Reserve_Data  True

# OCR Service Logs
[INPUT]
  Name          forward
  Tag           ocr.logs
  Listen        0.0.0.0
  Port          24225

[OUTPUT]
  Name          opensearch
  Match         ingredient-scan.*
  Host          ${opensearch_host}
  Port          9200
  HTTP_User     ${opensearch_user}
  HTTP_Passwd   ${opensearch_pass}
  Index         ingredient-scan-logs
  Logstash_Format On
  Logstash_Prefix ingredient-scan
  Logstash_DateFormat %Y.%m.%d
  Retry_Limit   2
  Suppress_Type_Name On
  tls           On
  tls.verify    Off

[OUTPUT]
  Name          opensearch
  Match         ocr.*
  Host          ${opensearch_host}
  Port          9200
  HTTP_User     ${opensearch_user}
  HTTP_Passwd   ${opensearch_pass}
  Index         ocr-logs
  Logstash_Format On
  Logstash_Prefix ocr
  Logstash_DateFormat %Y.%m.%d