spring:
  application:
    name: ingredient-scan-scan
#  lifecycle:
#    timeout-per-shutdown-phase: "3m"
  mandatory-file-encoding: UTF-8
  main:
    banner-mode: off
  webflux:
    multipart:
      max-in-memory-size: 256KB
      max-disk-usage-per-part: 1GB
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL
#    deserialization:
#      accept-single-value-as-array: true
  cloud:
    aws:
      credentials:
        access-key: minioadmin
        secret-key: minioadminpassword
      region:
        static: us-east-1
      endpoint: http://localhost:9000
      s3:
        # Ключевой параметр для MinIO
        endpoint: http://localhost:9000
        path-style-access-enabled: true
        bucket:
          name: photos # Имя вашего бакета в MinIO
  docker:
    compose:
      enabled: true
      file: file:${user.dir}/deploy/docker-compose-dev.yml
      wait:
        enabled: true
        timeout: 180s
      lifecycle-management: start-and-stop
#      lifecycle-management: start-only


  kafka:
    streams:
      auto-startup: false
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: ingredient-scanner-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

server:
  port: 8081
  servlet:
    context-path: /v1
#  shutdown: graceful

logging:
  level:
    # Для отслеживания запросов
    org.springframework.web: DEBUG
    org.springframework.web.servlet: DEBUG

    # Для отслеживания регистрации контроллеров
    org.springframework.boot.autoconfigure: DEBUG
    org.springframework.context.annotation.ClassPathBeanDefinitionScanner: DEBUG

    # Ваши пакеты
    net.otuskotlin.ingredientscan: DEBUG

    # Spring MVC
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE

    org.springframework.boot.docker.compose: DEBUG

    io.awspring.cloud: DEBUG