spring:
  application:
    name: ingredient-scan-scan
  mandatory-file-encoding: UTF-8
  main:
    banner-mode: off
  webflux:
    multipart:
      max-in-memory-size: 256KB
      max-disk-usage-per-part: 1GB
      max-parts: 10
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: NON_NULL

  cloud:
    aws:
      credentials:
        access-key: ${SPRING_CLOUD_AWS_CREDENTIALS_ACCESS_KEY:minioadmin}
        secret-key: ${SPRING_CLOUD_AWS_CREDENTIALS_SECRET_KEY:minioadminpassword}
      region:
        static: ${SPRING_CLOUD_AWS_REGION_STATIC:us-east-1}
      endpoint: ${SPRING_CLOUD_AWS_ENDPOINT:http://minio:9000}
      s3:
        endpoint: ${SPRING_CLOUD_AWS_ENDPOINT:http://minio:9000}
        path-style-access-enabled: true
        bucket:
          name: ${SPRING_CLOUD_AWS_S3_BUCKET_NAME:photos}

  docker:
    compose:
      enabled: false   # отключаем встроенный compose в prod

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9093}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID:ingredient-scanner-group}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

  r2dbc:
    url: r2dbc:postgresql://postgres:5432/ingredient_scan
    username: ingredient_user
    password: ${DB_PASSWORD:ingredient_pass}
    pool:
      max-size: 10
      initial-size: 2

  datasource:
    url: jdbc:postgresql://postgres:5432/ingredient_scan
    username: ingredient_user
    password: ${DB_PASSWORD:ingredient_pass}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    url: jdbc:postgresql://postgres:5432/ingredient_scan
    user: ingredient_user
    password: ${DB_PASSWORD:ingredient_pass}
    driver-class-name: org.postgresql.Driver
    default-schema: public

app:
  upload:
    max-files: 5
  security:
    internal:
      token: ${INTERNAL_API_TOKEN:default-secret-123}
      prefix: /v1/internal
  kafka:
    topics:
      bootstrap-servers: ${APP_KAFKA_TOPICS_BOOTSTRAP_SERVERS:${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9093}}
      partitions: 1
      replication-factor: 1

server:
  port: 8080
  shutdown: graceful

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    org.springframework.boot: INFO
    net.otuskotlin.ingredientscan: INFO
    org.apache.kafka: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
  endpoint:
    health:
      show-details: always
#      show-details: when-authorized
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
